export const GET_COMPANIES = "GET_COMPANIES";
export const DEL_COMPANIES = "DEL_COMPANIES";
export const POST_COMPANIES = "POST_COMPANIES";
export const UPDATE_COMPANIES    = "UPDATE_COMPANIES";

export const GET_ROLES = "GET_ROLES";
export const CREATE_ROLE = "CREATE_ROLE";
export const EDIT_ROLE = "EDIT_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";

export const GET_MENU = "GET_MENU"; //fetch
export const DEL_MENU = "DEL_MENU"; //delete
export const ADD_MENU = "ADD_MENU"; //add
export const PUT_MENU = "PUT_MENU"; //update

export const GET_MENUACCESS = "GET_MENUACCESS";
export const CREATE_MENUACCESS = "CREATE_MENUACCESS";
export const EDIT_MENUACCESS = "EDIT_MENUACCESS";
export const DELETE_MENUACCESS = "DELETE_MENUACCESS";

export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DEL_PRODUCT = "DEL_PRODUCT";

export const GET_TSOUVERNIR = "GET_TSOUVERNIR";
export const CREATE_TSOUVERNIR = "CREATE_TSOUVERNIR";
export const UPDATE_TSOUVENIR = "UPDATE_TSOUVENIR";
export const DEL_TSOUVERNIR = "DEL_TSOUVERNIR";

export const GET_TSOUVERNIR_ITEM = "GET_TSOUVERNIR_ITEM";
export const GET_EMPLOYEE = "GET_EMPLOYEE";

export const GET_SOUVERNIR_ITEM = "GET_SOUVERNIR_ITEM";
export const CREATE_SOUVENIR_ITEM = "CREATE_SOUVENIR_ITEM";

export const GET_QUESTIONER = "GET_QUESTIONER"
export const CREATE_QUESTIONER = "CREATE_QUESTIONER";
export const UPDATE_QUESTIONER = "UPDATE_QUESTIONER";

export const CREATE_DETAIL = "CREATE_DETAIL";
export const UPDATE_DETAIL = "UPDATE_DETAIL";
